Repository abubakarp789/Churn_Predictor, pull requests merged in 2024-10, with the labels that each got.

#5 Update ReadME.md
  README.md
Labels: good first issue, hacktoberfest-accepted, gssoc-ext, level1

#7 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#8 Revert "Added MIT license in project"
  LICENSE
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#9 Add MIT license in project #4
  LICENSE
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#12 Enhance homepage layout and design
  templates/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#14 Update index.html
  templates/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#15 Update ReadME.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#16 Update Prediction.html
  templates/prediction.html
Labels: hacktoberfest-accepted, hacktoberfest

#20 Index file Updated
  templates/index.html
  templates/style.css
Labels: hacktoberfest-accepted, hacktoberfest
